# Generated by Django 4.1.2 on 2022-11-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_categorydata_options_clothsdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothsdata',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
